name: 'Tests & Linting'

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: []

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run ci-test
      - run: npm run check
      - run: npm run build
  